language: python
sudo: false
python:
  - "3.4"
  - "3.5"

# command to install dependencies
install:
  - python setup.py build sdist
  - pip install -r requirements-tests.txt
# command to run tests
script: pytest tests/
